[manifest]
version = "1.0.0"
dump_lua = true
priority = 10

# Use Chaldur challenges page on toggle
# G.UIDEF.run_setup()
[[patches]]
[patches.pattern]
target = 'functions/UI_definitions.lua'
pattern = '''
tab_definition_function = G.UIDEF.challenges,
'''
position = 'at'
payload = '''
tab_definition_function = (Chaldur.config.use and G.UIDEF.challenge_setup_option or G.UIDEF.challenges),
'''
match_indent = true